server:
  port: 9090

spring:
  application:
    name: grpc-client-local
  main:
    banner-mode: off

grpc:
  client:
    simple-service:
      address: static://localhost:9898
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiation-type: PLAINTEXT
